# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#  base_url: https://ktkhassio.duckdns.org:8123
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate

camera:
  - platform: mjpeg
    name: Camera garage
    mjpeg_url: http://192.168.178.210:8889

# Device Tracker
device_tracker:
  - platform: fritz
    host: 192.168.178.1
    interval_seconds: 10
    consider_home: 180
    new_device_defaults:
      track_new_devices: true


#MQTT
mqtt:
  broker: hassio.fritz.box
  client_id: home_assistant
  username: !secret mqtt_broker_username1
  password: !secret mqtt_broker_password1

#Uitlezen nefit
climate:
  - platform: mqtt
    name: NefitEasy
    modes:
      - "heat"
    current_temperature_topic: "nefit/status"
    current_temperature_template: "{{ value_json['in house temp']}}"
    temperature_state_topic: "nefit/status"
    temperature_state_template: "{{ value_json['temp setpoint']}}"
    temperature_command_topic: "nefit/set/temp"
    min_temp: 10
    max_temp: 22    

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

