# Uitlezen nefit Status
- platform: mqtt
  state_topic: "nefit/status"
  name: "Temperatuur"
  device_class: temperature
  unit_of_measurement: "°C"
  value_template: "{{ value_json['in house temp']}}"
- platform: mqtt
  state_topic: "nefit/status"
  name: "Set Temp"
  device_class: temperature
  unit_of_measurement: "°C"
  value_template: "{{ value_json['temp setpoint']}}" 
- platform: mqtt
  state_topic: "nefit/status"
  name: Buitentemperatuur
  unit_of_measurement: "°C"
  value_template: "{{ value_json['outdoor temp']}}" 
- platform: mqtt
  state_topic: "nefit/status"
  name: "Boiler Indicator"
  value_template: "{{value_json['boiler indicator']}}"

#PVOutput waarden uitlezen
- platform: pvoutput
  system_id: 36378
  api_key: !secret pv_api_key
  scan_interval: 150
- platform: template
  sensors:
    power_consumption:
      value_template: '{% if is_state_attr("sensor.pvoutput", "power_consumption", "NaN") %}0{% else %}{{ state_attr("sensor.pvoutput", "power_consumption") }}{% endif %}'
      friendly_name: 'Huidig gebruik'
      unit_of_measurement: 'Watt'
      icon_template: 'mdi:power-plug'
    energy_consumption:
      value_template: '{{ "%0.1f"|format(state_attr("sensor.pvoutput", "energy_consumption")|float/1000) }}'
      friendly_name: 'Gebruikt vandaag'
      unit_of_measurement: 'kWh'
      icon_template: 'mdi:flash'
    power_generation:
      value_template: '{% if is_state_attr("sensor.pvoutput", "power_generation", "NaN") %}0{% else %}{{ states.sensor.pvoutput.attributes.power_generation }}{% endif %}'
      friendly_name: 'Huidig opgewekt vermogen'
      unit_of_measurement: 'Watt'
      icon_template: 'mdi:solar-power'
    energy_generation:
      value_template: '{% if is_state_attr("sensor.pvoutput", "energy_generation", "NaN") %}0{% else %}{{ "%0.2f"|format(states.sensor.pvoutput.attributes.energy_generation|float/1000) }}{% endif %}'
      friendly_name: 'Opgewekt vandaag'
      unit_of_measurement: 'kWh'
      icon_template: 'mdi:flash'
      

