# Uitlezen nefit Status
- platform: mqtt
  state_topic: "nefit/status"
  name: "Temperatuur"
  device_class: temperature
  unit_of_measurement: "°C"
  value_template: "{{ value_json['in house temp']}}"
- platform: mqtt
  state_topic: "nefit/status"
  name: "Set Temp"
  device_class: temperature
  unit_of_measurement: "°C"
  value_template: "{{ value_json['temp setpoint']}}" 
- platform: mqtt
  state_topic: "nefit/status"
  name: Buitentemperatuur
  unit_of_measurement: "°C"
  value_template: "{{ value_json['outdoor temp']}}" 
